### ISSUE TITLE
[Question] クライアント側リクエスト時のCORSエラーについて

### ISSUE THREAD

**Issue by seiei-sogen** [ReactLibraries/use-ssr#1]
お世話になります。

日本語で失礼いたします。
[use-ssr](https://github.com/ReactLibraries/use-ssr) の使用法について、質問させていただいたいのですが、よろしいでしょうか。

事象が起こった状況は、Next.jsでuse-ssrを使いました。
ホットペッパーAPIを使い、クライアント側のデータフェッチで、CORSエラーが出ます。

```
Access to fetch at 'http://webservice.recruit.co.jp/hotpepper/gourmet/v1/?format=json&key=XXXXX&large_area=Z011' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
index.tsx?19a0:91          

GET http://webservice.recruit.co.jp/hotpepper/gourmet/v1/?format=json&key=XXXXX&large_area=Z011 net::ERR_FAILED 200
```

![スクリーンショット 2022-02-09 203623](https://user-images.githubusercontent.com/66318252/153192427-7a0a772f-5851-440c-a515-c251d6905791.png)

ホットペッパーAPI
https://webservice.recruit.co.jp/doc/hotpepper/reference.html

[use-ssr](https://github.com/ReactLibraries/use-ssr)を使用時に、CORSエラーが出る場合はどのような、対処をすればよろしいでしょうか。
もし何か、手法がございましたら、お教えいただけますと幸いです。

（追伸）
ちなみに、これを回避するために、Next.jsのAPI routeを利用しました。
しかし、なぜか、use-ssr内ですと、http://localhost:3000/api/restaurant のようなAPI routeが404になり、この手法もうまくいきませんでした。
（Recoilのような状態管理のアプリでは、404にならず、正常にデータが取得できます。）

こちらは、上記のCORSエラーとはまた別の問題かもしれません。

参考にした記事

1-5. Create React Appとの違いを知る(API)
https://zenn.dev/terrierscript/books/2020-09-next-js/viewer/1-5

**Comment by SoraKumo001** [comment]
`typeof window === "undefined"`
などでサーバーとクライアントどちらで実行されているか判断して、適切にURLを変更する必要があります
サーバからはlocalhostにアクセスできても、クライアントからは自身の環境を参照してしまいます

**Comment by seiei-sogen** [comment]
@SoraKumo001 様

ご回答いただきありがとうございます。

> typeof window === "undefined"
> などでサーバーとクライアントどちらで実行されているか判断して、適切にURLを変更する必要があります

こちら、承知いたしました。
こちらの issue は一旦クローズさせていただきます。

ありがとうございました。
